FROM mongo
MAINTAINER yy

RUN apt-get update
RUN apt-get upgrade

RUN apt-get install -y nginx
RUN apt-get clean

# ENV STATIC_NG_DIR=/usr/share/nginx/html/
ENV NG_CONFIG_DIR=/etc/nginx/conf.d/

COPY ./forker.cn.static.conf NG_CONFIG_DIR

RUN nginx

# 仅仅是定义，和宿主机的 docker -p 11:11 是不一样的
# https://yeasy.gitbook.io/docker_practice/image/dockerfile/expose
EXPOSE 10010
EXPOSE 27017
